services:

  # docker run command:
  # docker run -i -d --rm --name=paste.bin.ingest.api --mount type=bind,source=C:/Users/null/source/repos/paste.bin.ingest/.docker.files/data,target=/bin/paste.bin.ingest/data --mount type=bind,source=C:/Users/null/source/repos/paste.bin.ingest/.docker.files/api.logs,target=/bin/paste.bin.ingest/logs -e ASPNETCORE_ENVIRONMENT=dev chrwalte/paste.bin.ingest.api:build

  paste.bin.ingest.api:
    container_name: paste.bin.ingest.api
    hostname: paste.bin.ingest.api
    image: chrwalte/paste.bin.ingest.api:build
    ports:
      - 8080:80
    environment:
      # ASPNETCORE_ENVIRONMENT: "prod"
      ASPNETCORE_ENVIRONMENT: "dev"
    volumes:
      - ".docker-compose.files/data:/bin/paste.bin.ingest/data/"
      - ".docker-compose.files/api.logs:/bin/paste.bin.ingest/logs/"
    networks:
      - paste.bin.ingest.network
    restart: unless-stopped

  # docker run command:
  # docker run -i -d --rm --name=paste.bin.ingest.cmd --mount type=bind,source=C:/Users/null/source/repos/paste.bin.ingest/.docker.files/data/,target=/bin/paste.bin.ingest/data/ --mount type=bind,source=C:/Users/null/source/repos/paste.bin.ingest/.docker.files/cmd.logs/,target=/bin/paste.bin.ingest/logs/ -e ENVIRONMENT=dev chrwalte/paste.bin.ingest.cmd:build

  paste.bin.ingest.cmd:
    container_name: paste.bin.ingest.cmd
    hostname: paste.bin.ingest.cmd
    image: chrwalte/paste.bin.ingest.cmd:build
    environment:
      # ENVIRONMENT: "prod"
      ENVIRONMENT: "dev"
    volumes:
      - ".docker-compose.files/data:/bin/paste.bin.ingest/data/"
      - ".docker-compose.files/cmd.logs:/bin/paste.bin.ingest/logs/"
    networks:
      - paste.bin.ingest.network
    restart: unless-stopped

networks:

  paste.bin.ingest.network:
    name: paste.bin.ingest.network
